// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationsExample;

#nullable disable

namespace MigrationsExample.Migrations
{
    [DbContext(typeof(DungeonDbContext))]
    [Migration("20220511053706_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MigrationsExample.DungeonRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DungeonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomsCleared")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DungeonRun", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
