// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationsExample;

#nullable disable

namespace MigrationsExample.Migrations
{
    [DbContext(typeof(DungeonDbContext))]
    [Migration("20220510090410_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MigrationsExample.DungeonRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("int");

                    b.Property<string>("DungeonName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoomsCleared")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DungeonRun", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
